### ISSUE TITLE
Error running "python train.py task=Hover total_frames=100_000_000 eval_interval=60 headless=true"

### ISSUE THREAD

**Issue by JJJJJllll** [btx0424/OmniDrones#49]
Hi there, I hope it finds you well.
I'm using Issac Sim 2023.1.1. I followed through your instructions on Installation and successfully came to "Running the RL Scripts".
I can successfully run `python train.py task=Hover headless=true` and see results on wandb.
but I cannot run `python train.py task=Hover total_frames=100_000_000 eval_interval=60 headless=true`
the error message is: 
```
2024-02-26 12:44:35 [534,839ms] [Error] [omni.physx.plugin] Transformation change on non-root links is not supported. Link: /World/envs/env_1237/Firefly_0/rotor_4
2024-02-26 12:44:35 [534,839ms] [Error] [omni.physx.plugin] Transformation change on non-root links is not supported. Link: /World/envs/env_124/Firefly_0/rotor_4
2024-02-26 12:44:35 [534,839ms] [Error] [omni.physx.plugin] Transformation change on non-root links is not supported. Link: /World/envs/env_2141/Firefly_0/rotor_4
2024-02-26 12:44:35 [534,839ms] [Error] [omni.physx.plugin] Transformation change on non-root links is not supported. Link: /World/envs/env_1242/Firefly_0/rotor_4
2024-02-26 12:44:35 [534,843ms] [Error] [omni.physx.plugin] PhysX error: PxArticulationLink::setGlobalPose(): it is illegal to call this method if PxSceneFlag::eENABLE_DIRECT_GPU_API is enabled!, FILE /buildAgent/work/eb2f45c4acc808a0/physx/source/physx/src/NpArticulationLink.cpp, LINE 343
2024-02-26 12:44:35 [534,843ms] [Error] [omni.physx.plugin] PhysX error: PxArticulationLink::setGlobalPose(): it is illegal to call this method if PxSceneFlag::eENABLE_DIRECT_GPU_API is enabled!, FILE /buildAgent/work/eb2f45c4acc808a0/physx/source/physx/src/NpArticulationLink.cpp, LINE 343
2024-02-26 12:44:35 [534,843ms] [Error] [omni.physx.plugin] PhysX error: PxArticulationLink::setGlobalPose(): it is illegal to call this method if PxSceneFlag::eENABLE_DIRECT_GPU_API is enabled!, FILE /buildAgent/work/eb2f45c4acc808a0/physx/source/physx/src/NpArticulationLink.cpp, LINE 343
2024-02-26 12:44:36 [535,909ms] [Error] [omni.physx.tensors.plugin] GPU tensor function getRootTransforms can only be called after at least one simulation step was performed!
```

Can you help me with it?

**Comment by btx0424** [comment]
Hi there. I believe Isaac Sim 2023.1.0 (hotfix or not) does not have this issue. I recommend not using Isaac Sim 2023.1.1 for now. I will look into the problem and get back to you.

**Comment by JJJJJllll** [comment]
Hi, now I'm using Issac Sim 2023.1.0.hotfix, python3.7, and I **cannot import pytorch,** would you please help me with it?
It is at the beginning, after env creating and file copying.
I can run `python -c "from omni.isaac.kit import SimulationApp"`, but when I run `python -c "import torch; print(torch.__path__)"`, problems happen and they are like that:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/comb/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/__init__.py", line 454, in <module>
    ''').strip()) from None
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
```
Looking forward to your reply!

**Comment by kisisjrlly** [comment]
set prepare_contact_sensors to false in _RigidPrimView _init__

**Comment by Everloom-129** [comment]
Hi @kisisjrlly , could you share more details on how to fix this issue?
I tried to set in `/home/exx/Projects/RL_Drone/OmniDrones-1121/omni_drones/views/__init__.py`
but I still cannot display the trained policy
