### ISSUE TITLE
TDMPC Error

### ISSUE THREAD

**Issue by ErinTUDelft** [btx0424/OmniDrones#67]
Thank you for creating this library, it really is amazing! However, when running train.py (algo=tdmpc, task=Hover) from /scripts I get the following error: 
```
Traceback (most recent call last):
  File "/home/erin/Thesis/OmniDrones/scripts/train.py", line 104, in main
    policy = ALGOS[cfg.algo.name.lower()](
TypeError: TDMPCPolicy.__init__() got multiple values for argument 'device'
```

When running the same command from /scripts_paper I get this error:
```
 File "/home/erin/anaconda3/envs/OmniDrones310/lib/python3.10/copy.py", line 161, in deepcopy
  File "/home/erin/Thesis/OmniDrones/scripts_paper/train.py", line 172, in main
    collector = SyncDataCollector(
  File "/home/erin/Thesis/Utils/rl/torchrl/collectors/collectors.py", line 539, in __init__
    (self.policy, self.get_weights_fn,) = self._get_policy_and_device(
  File "/home/erin/Thesis/Utils/rl/torchrl/collectors/collectors.py", line 178, in _get_policy_and_device
    policy = deepcopy(policy)
----------
    rv = reductor(4)
TypeError: cannot pickle 'omni.kit.app._app.IApp' object
```

Which of the two training files would you recommend using? And how can I resolve this issue?
Kind regards,
Erin

**Comment by btx0424** [comment]
Really sorry for the delayed reply. I have been busy with another project lately.

Unfortunately, we found TDMPC (our implementation) performs poorly on tasks beyond hovering and simple tracking. The critical issue is that planning is too time-consuming to be used in a massively parallelized setting. Therefore the algorithm did not appear in the paper and is no longer maintained. I would suggest not using it unless you have specific interest in model-based methods.

**Comment by Sgmltd** [comment]
> TypeError: TDMPCPolicy.__init__() got multiple values for argument 'device'

@ErinTUDelft Hello, have you now solved the related bug about the tdmpc algorithm? I've run other algorithms and I'm getting the same error as yours:
`
 TypeError: XXXXPolicy.__init__() got multiple values for argument 'device'
`

How did you get this algorithm to work? Looking forward to your answers. Thanks!
