### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GetPath'

### ISSUE THREAD

**Issue by HoiyuWu** [btx0424/OmniDrones#77]
When I wanted to verify whether it was installed correctly and run `python train.py algo=ppo headless=true wandb.entity=YOUR_WANDB_ENTITY`, an error AttributeError: 'NoneType' object has no attribute 'GetPath' occurred

`Error executing job with overrides: ['algo=ppo', 'headless=true']
Traceback (most recent call last):
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/studj/OmniDrones/scripts/train.py", line 51, in main
    base_env = env_class(cfg, headless=cfg.headless)
  File "/home/studj/Documents/rl/torchrl/envs/common.py", line 177, in __call__
    instance: EnvBase = super().__call__(*args, **kwargs)
  File "/home/studj/OmniDrones/omni_drones/envs/single/hover.py", line 122, in __init__
    super().__init__(cfg, headless)
  File "/home/studj/OmniDrones/omni_drones/envs/isaac_env.py", line 134, in __init__
    global_prim_paths = self._design_scene()
  File "/home/studj/OmniDrones/omni_drones/envs/single/hover.py", line 192, in _design_scene
    kit_utils.create_ground_plane(
  File "/home/studj/OmniDrones/omni_drones/utils/kit.py", line 84, in create_ground_plane
    collision_prim_path = prim_utils.get_prim_path(
  File "/home/studj/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.isaac.core/omni/isaac/core/utils/prims.py", line 349, in get_prim_path
    return prim.GetPath()
AttributeError: 'NoneType' object has no attribute 'GetPath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studj/OmniDrones/scripts/train.py", line 246, in <module>
    main()
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    if _is_env_set("HYDRA_FULL_ERROR") or is_under_debugger():
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/hydra/_internal/utils.py", line 172, in is_under_debugger
    frames = inspect.stack()
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/inspect.py", line 1673, in stack
    return getouterframes(sys._getframe(1), context)
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/inspect.py", line 1650, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/inspect.py", line 1624, in getframeinfo
    lines, lnum = findsource(frame)
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/wandb/util.py", line 219, in __getattribute__
    state.load()
  File "/home/studj/anaconda3/envs/sim/lib/python3.10/site-packages/wandb/util.py", line 212, in load
    self.module.__spec__.loader.exec_module(self.module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/studj/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.pip.cloud/pip_prebundle/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/studj/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.pip.cloud/pip_prebundle/azure/storage/blob/_blob_client.py", line 17, in <module>
    from typing_extensions import Self
ImportError: cannot import name 'Self' from 'typing_extensions' (/home/studj/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/kit/exts/omni.kit.pip_archive/pip_prebundle/typing_extensions.py)`

**Comment by INDEX108** [comment]
I also had the same issue, did you fix it?

**Comment by HoiyuWu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
