### ISSUE TITLE
Error when running python train.py task=Hover total_frames=100_000_000 eval_interval=60 headless=true

### ISSUE THREAD

**Issue by godk1122** [btx0424/OmniDrones#86]
hi！
 I'm using isaac-sim:4.0.0, when running python `train.py task=Hover total_frames=100_000_000 eval_interval=60 headless=true` (enable evaluation (which would record a video clip for visulization) during training), there is an error:

Error executing job with overrides: ['task=Hover', 'total_frames=100_000_000', 'eval_interval=60', 'headless=true']
Traceback (most recent call last):
  File "/omni_wjk/scripts/train.py", line 183, in main
    info.update(evaluate())
  File "/isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/omni_wjk/scripts/train.py", line 123, in evaluate
    trajs = env.rollout(
  File "/root/anaconda3/envs/sim/lib/python3.10/site-packages/torchrl/envs/common.py", line 2432, in rollout
    tensordicts = self._rollout_nonstop(**kwargs)
  File "/root/anaconda3/envs/sim/lib/python3.10/site-packages/torchrl/envs/common.py", line 2530, in _rollout_nonstop
    callback(self, tensordict)
  File "/omni_wjk/omni_drones/utils/torchrl/env.py", line 95, in __call__
    frame = env.render(mode="rgb_array")
  File "/omni_wjk/omni_drones/envs/isaac_env.py", line 377, in render
    return rgb_data[:, :, :3]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

it seems like rgb_data is empty, how can i fix this problem? Thanks for your help!

**Comment by S-Kotala** [comment]
Hey, 

I am running into the same issue as well so I am writing a comment to check back on this thread later.
